version: 2
updates:
  # 1. Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "qc-310"

  # 2. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "qc-310"

  # 3. Terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "qc-310"

  # 4. Docker
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "qc-310"
