version: "3.9"

services:
  dog-gallery:
    build: .
    container_name: thesalo-gallery
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_EMAILS=${ALLOWED_EMAILS}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - MAX_IMAGE_SIZE=${MAX_IMAGE_SIZE:-1920}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped